"""Generate a migration index from migration docstrings.

Reads every ``NNN_*.py`` in ``app/migrations/``, extracts the first non-empty
line of each module docstring and whether it declares ``FATAL = True``, and
writes a Markdown table to ``app/migrations/INDEX.md``.

Re-run after adding a migration:

    python tools/gen_migration_index.py
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "app" / "migrations"
INDEX_PATH = MIGRATIONS_DIR / "INDEX.md"
_NAME_RE = re.compile(r"^\d{3}_.*\.py$")


def _first_docstring_line(source: str) -> str:
    doc = ast.get_docstring(ast.parse(source))
    if not doc:
        return "(no docstring)"
    for line in doc.splitlines():
        if line.strip():
            return line.strip()
    return "(no docstring)"


def _is_fatal(source: str) -> bool:
    for node in ast.parse(source).body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "FATAL" for t in node.targets
        ):
            return isinstance(node.value, ast.Constant) and node.value.value is True
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "FATAL"
        ):
            value = node.value
            return isinstance(value, ast.Constant) and value.value is True
    return False


def build_index() -> str:
    rows = []
    for path in sorted(MIGRATIONS_DIR.glob("*.py")):
        if not _NAME_RE.match(path.name):
            continue
        source = path.read_text(encoding="utf-8")
        flag = " **FATAL** —" if _is_fatal(source) else ""
        rows.append(f"| `{path.stem}` |{flag} {_first_docstring_line(source)} |")
    header = (
        "# Migration Index\n\n"
        "_Auto-generated by `tools/gen_migration_index.py` — do not edit by hand._\n\n"
        "The runner discovers every `*.py` here except `__init__.py`/`runner.py`,\n"
        "applies them sorted by filename stem, and records each in\n"
        "`schema_migrations`. A **FATAL** migration blocks startup if it fails. A\n"
        "non-FATAL failure does NOT block startup, but the runner stops the\n"
        "remaining pending-migration chain at that exception — so cleanup-style\n"
        "migrations must swallow their own operational errors.\n\n"
        "| Migration | Summary |\n|---|---|\n"
    )
    return header + "\n".join(rows) + "\n"


def main() -> None:
    INDEX_PATH.write_text(build_index(), encoding="utf-8")
    print(f"Wrote {INDEX_PATH}")


if __name__ == "__main__":
    main()
